CREATE DATABASE IF NOT EXISTS test;

SHOW DATABASES;

CREATE TABLE IF NOT EXISTS custom_standard_services (
pk_auto_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
fk_service_id INT NULL DEFAULT NULL,
fk_service_name VARCHAR(254) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS itsm_sla_default(
pk_auto_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
callclass VARCHAR(64) NOT NULL,
appcode VARCHAR(16) NULL DEFAULT NULL,
fk_slad INT NULL DEFAULT NULL,
fk_slad_name VARCHAR(254) NULL DEFAULT NULL,
fk_priority VARCHAR (254) NULL DEFAULT NULL,
flg_use_sla_rules INT NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS itsm_sla_rules(
pk_auto_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
seq INT NOT NULL,
sla_rule VARCHAR(64) NOT NULL,
appcode VARCHAR(16) NULL DEFAULT NULL,
callclass VARCHAR(64) NOT NULL,
rulename VARCHAR(124) NOT NULL,
longest_sla VARCHAR(8) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sw_settings(
pk_setting VARCHAR(254) NOT NULL PRIMARY KEY,
setting_value VARCHAR(254) NULL DEFAULT NULL,
description VARCHAR(254) NULL DEFAULT NULL,
toplevelcategory VARCHAR(254) NULL DEFAULT NULL
);

SHOW FULL TABLES;

SELECT * FROM information_schema.Tables\g
--
-- SHOW COLUMNS FROM custom_standard_services;
-- SHOW COLUMNS FROM   itsm_sla_rules;
